# 3.1

In [14]:
import numpy as np

In [15]:
a=np.arange(24).reshape(3,4,2)

In [16]:
print a

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [33]:
a[2,2,1] 

21

In [32]:
a[1:]

array([[[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [31]:
a[0:1]

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

Numpy массивы являются более компактными, чем списки. Доступ в чтения и записи элементов также быстрее с NumPy.
Список А Python представляет собой массив указателей на объекты Python, по крайней мере, 4 байта на указатель плюс 16 байтов для даже самого маленького объекта Python (4 для указателя типа, 4 для счетчика ссылок, 4 для значения). Массив NumPy представляет собой массив однородных значений - значения одинарной точности чисел занимают 4 байта каждое, а значения с двойной точностью 8 байт.

# 3.2

In [11]:
import numpy as np 
from timeit import Timer

Nelements = 10000
Ntimeits = 10000

x = np.arange(Nelements)
y = range(Nelements)

t_numpy = Timer("x.sum()", "from __main__ import x")
t_list = Timer("sum(y)", "from __main__ import y")
print "numpy: %.3e" % (t_numpy.timeit(Ntimeits)/Ntimeits,)
print "list:  %.3e" % (t_list.timeit(Ntimeits)/Ntimeits,)

numpy: 1.560e-05
list:  1.178e-04


Тестим видим что сумма numpy в 10х быстрее чем сумма списка.

# 3.3

Ниже мой аналог linspace

In [8]:
def grid(a,b,n):
    diff = (float(b) - a)/(n - 1)
    return [diff * i + a  for i in range(n)]


In [54]:
np.linspace(1, 6.0, num=5)

array([ 1.  ,  2.25,  3.5 ,  4.75,  6.  ])

In [55]:
res = grid(1,6,5)
print res

[1.0, 2.25, 3.5, 4.75, 6.0]


Проверили - все работает так же как у linspace. Урррра!

In [56]:
type(res)

list

Проверили тип - я молодец! ◕‿◕

In [9]:
from timeit import Timer
import numpy as np 

Nelements = 10000
Ntimeits = 10000


t_numpy = Timer(lambda: np.linspace(0, Nelements, num=Nelements))
t_list = Timer(lambda: grid(0, Nelements, Nelements))
print "numpy: %.3e" % (t_numpy.timeit(Ntimeits)/Ntimeits,)
print "list:  %.3e" % (t_list.timeit(Ntimeits)/Ntimeits,)

numpy: 4.376e-05
list:  2.029e-03


Упс..список работает гораздно мелдленнее(